[Unit]
Wants=network-online.target avahi-daemon.service
After=network-online.target avahi-daemon.service

[Service]
ExecStart=
ExecStart=/usr/bin/librespot --name Sala --backend alsa --device plughw:Loopback,0,0 --bitrate 320
Restart=always
RestartSec=5
