"use client";

import { useState } from "react";

export type StoredProfile = { name:string; title?:string; description?:string; valid:boolean; lastModified:number; aliasOf?:string|null };
export type TransferParts = { crossovers:boolean; equalizers:boolean; dynamics:boolean; mixer:boolean };

export function ProfileManager({profiles,activeName,unsaved,busy,onClose,onLoad,onTransfer,onCreate,onDelete}:{profiles:StoredProfile[];activeName:string;unsaved:boolean;busy:boolean;onClose:()=>void;onLoad:(name:string)=>Promise<boolean>;onTransfer:(source:string,destination:string,parts:TransferParts)=>Promise<void>;onCreate:(source:string|null,name:string)=>Promise<void>;onDelete:(name:string)=>Promise<void>}) {
  const names=profiles.map((item)=>item.name);
  const [selected,setSelected]=useState(activeName);
  const [source,setSource]=useState(names.find((name)=>name!==activeName)??activeName);
  const [destination,setDestination]=useState(activeName);
  const [createSource,setCreateSource]=useState(activeName);
  const [createName,setCreateName]=useState("");
  const [parts,setParts]=useState<TransferParts>({crossovers:true,equalizers:true,dynamics:false,mixer:false});
  const [working,setWorking]=useState(false);
  const [error,setError]=useState("");
  const [notice,setNotice]=useState("");
  const [operation,setOperation]=useState<"load"|"other">("other");
  const toggle=(key:keyof TransferParts)=>setParts((current)=>({...current,[key]:!current[key]}));
  const selectedParts=Object.values(parts).filter(Boolean).length;
  const run=async(action:()=>Promise<void|boolean>,success="",kind:"load"|"other"="other")=>{setWorking(true);setOperation(kind);setError("");setNotice("");try{const completed=await action();if(completed!==false&&success)setNotice(success);}catch(reason){setError(reason instanceof Error?reason.message:"Operação de perfil não concluída");}finally{setWorking(false);}};
  const normalizedCreateName=(()=>{const value=createName.trim();if(!value)return "";return value.toLowerCase().endsWith(".yml")?value:`${value}.yml`;})();
  const createNameValid=/^[A-Za-z0-9][A-Za-z0-9._-]*\.yml$/i.test(normalizedCreateName)&&!normalizedCreateName.includes("..");
  const createExists=names.some((name)=>name.toLowerCase()===normalizedCreateName.toLowerCase());
  const create=(generic=false)=>void run(async()=>{if(!createNameValid)throw new Error("Use um nome simples terminado em .yml, sem espaços ou pastas.");if(createExists)throw new Error(`${normalizedCreateName} já existe e não será sobrescrito.`);await onCreate(generic?null:createSource,normalizedCreateName);setSelected(normalizedCreateName);setCreateName("");});
  const remove=()=>void run(async()=>{if(selected===activeName)throw new Error("O perfil ativo não pode ser apagado. Carregue outro perfil antes.");if(!window.confirm(`Apagar permanentemente ${selected}? Esta ação não altera o DSP atual.`))return;await onDelete(selected);setSelected(activeName);});
  return <div className="modal-backdrop"><section className="profile-manager" role="dialog" aria-modal="true" aria-label="Gerenciar perfis YAML">
    <header><div><small>PERFIS YAML · CAMILLADSP</small><h2>Gerenciar configurações</h2></div><div className="profile-live"><span>DSP ATIVO E EM EDIÇÃO</span><b>{activeName}</b><em className={unsaved?"pending":"saved"}>{unsaved?"ALTERAÇÕES NÃO SALVAS":"SALVO NO YAML"}</em></div><button onClick={onClose} aria-label="Fechar">×</button></header>
    <div className="profile-body">
      <aside className="profile-list"><small>ARQUIVOS DISPONÍVEIS</small>{profiles.map((profile)=><button key={profile.name} className={`${selected===profile.name?"selected":""} ${profile.name===activeName?"active":""}`} onClick={()=>setSelected(profile.name)}><span><b>{profile.name}</b><small>{profile.title||profile.description||"Perfil CamillaDSP"}</small></span>{profile.name===activeName&&<em>NO DSP</em>}</button>)}<button className="delete-profile" disabled={working||busy||selected===activeName} onClick={remove}>{selected===activeName?"PERFIL ATIVO PROTEGIDO":`APAGAR ${selected}`}</button><div className="profile-invariant"><i>●</i><span><b>ESPECTRO PROTEGIDO</b><small>camilla_tee · 6 saídas · 48 kHz</small></span></div></aside>
      <section className="transfer-panel"><div className="profile-load"><div><small>CARREGAR PERFIL</small><h3>Colocar um YAML no DSP</h3><p>Valida, protege a saída do espectro e confirma o arquivo ativo antes de atualizar a interface.</p></div><label><span>PERFIL PARA CARREGAR</span><select value={selected} onChange={(event)=>{setSelected(event.target.value);setNotice("");setError("");}}>{names.map((name)=><option key={name}>{name}</option>)}</select></label><button className="load-profile" disabled={working||busy||!selected||selected===activeName} onClick={()=>void run(()=>onLoad(selected),`${selected} está ativo no DSP e pronto para edição.`,"load")}>{working&&operation==="load"?"CARREGANDO…":selected===activeName?"JÁ ESTÁ NO DSP":`CARREGAR NO DSP`}</button>{unsaved&&selected!==activeName&&<em>Há alterações não salvas em {activeName}; será pedida confirmação.</em>}{notice&&operation==="load"&&<div className="profile-load-result" role="status"><i>✓</i><span><b>CARREGAMENTO CONFIRMADO</b><small>{notice}</small></span></div>}{error&&operation==="load"&&<div className="profile-load-result error" role="alert"><i>!</i><span><b>FALHA NO CARREGAMENTO</b><small>{error}</small></span></div>}</div><div className="profile-create"><div><small>NOVO PERFIL</small><h3>Criar com base ou começar limpo</h3><p>O modelo genérico preserva apenas as interfaces atuais; filtros, mixers e pipeline começam vazios.</p></div><label><span>USAR COMO BASE</span><select value={createSource} onChange={(event)=>setCreateSource(event.target.value)}>{names.map((name)=><option key={name}>{name}</option>)}</select></label><label><span>NOME DO NOVO ARQUIVO</span><input value={createName} onChange={(event)=>setCreateName(event.target.value)} onKeyDown={(event)=>{if(event.key==="Enter"&&!working&&!busy&&createNameValid&&!createExists)create();}} placeholder="camilladsp-novo.yml" spellCheck={false}/></label><button className="create-profile" disabled={working||busy||!createNameValid||createExists} onClick={()=>create()}>{working?"CRIANDO…":`CRIAR A PARTIR DE BASE`}</button><button className="create-profile generic" disabled={working||busy||!createNameValid||createExists} onClick={()=>create(true)}>CRIAR GENÉRICO</button>{createExists&&<em>Esse arquivo já existe; escolha outro nome.</em>}</div><div className="transfer-heading"><small>TRANSFERÊNCIA CONTROLADA</small><h3>Mover partes entre perfis</h3><p>O destino recebe somente os blocos marcados. Captura, dispositivos e a saída de análise espectral permanecem protegidos.</p></div><div className="transfer-route"><label><span>ORIGEM</span><select value={source} onChange={(event)=>setSource(event.target.value)}>{names.map((name)=><option key={name}>{name}</option>)}</select></label><b>→</b><label><span>DESTINO</span><select value={destination} onChange={(event)=>setDestination(event.target.value)}>{names.map((name)=><option key={name}>{name}</option>)}</select></label></div>
        <div className="transfer-parts"><label className={parts.crossovers?"selected":""}><input type="checkbox" checked={parts.crossovers} onChange={()=>toggle("crossovers")}/><span><b>CROSSOVERS</b><small>Highpass e lowpass, incluindo roteamento</small></span></label><label className={parts.equalizers?"selected":""}><input type="checkbox" checked={parts.equalizers} onChange={()=>toggle("equalizers")}/><span><b>EQUALIZAÇÃO</b><small>EQ gráfico, paramétrico, shelves e biquads</small></span></label><label className={parts.dynamics?"selected":""}><input type="checkbox" checked={parts.dynamics} onChange={()=>toggle("dynamics")}/><span><b>PROTEÇÃO E ALINHAMENTO</b><small>Delay, gain, limiter, volume e loudness</small></span></label><label className={parts.mixer?"selected":""}><input type="checkbox" checked={parts.mixer} onChange={()=>toggle("mixer")}/><span><b>MIXER E ROTEAMENTO</b><small>Ganhos, mutes, somas e distribuição dos canais</small></span></label></div>
        <div className="protected-parts"><span>SEMPRE PRESERVADO NO DESTINO</span><b>CAPTURA/FONTE</b><b>CAMILLA_TEE</b><b>6 SAÍDAS</b><b>SAMPLE RATE</b></div>{source===destination&&<div className="profile-warning">Escolha arquivos diferentes para origem e destino.</div>}{destination===activeName&&unsaved&&<div className="profile-warning">O destino está ativo e possui alterações não salvas. Salve antes de transferir.</div>}{error&&operation==="other"&&<div className="profile-warning error">{error}</div>}<button className="execute-transfer" disabled={working||busy||source===destination||selectedParts===0||(destination===activeName&&unsaved)} onClick={()=>void run(()=>onTransfer(source,destination,parts))}>{working&&operation==="other"?"VALIDANDO E CRIANDO BACKUP…":`TRANSFERIR PARA ${destination}`}</button>
      </section>
    </div>
  </section></div>;
}
